import pyautogui
import time

pyautogui.hotkey('ctrl', 'esc')
time.sleep(1)
pyautogui.write("g")
pyautogui.press('enter')
time.sleep(2)
pyautogui.write("y")
pyautogui.press('enter')
pyautogui.moveTo(600,200,2)
time.sleep(2)
pyautogui.leftClick()
pyautogui.write("boef, jopie en racist ruzies")
pyautogui.press('enter')
pyautogui.moveTo(None,400, 2)
pyautogui.leftClick()
pyautogui.moveTo(500,900,1)
pyautogui.leftClick()
pyautogui.press('volumeup', 25) 
time.sleep(1)
pyautogui.moveTo(859, None, 1)
pyautogui.leftClick()
pyautogui.moveTo(1100, 600,1)
pyautogui.doubleClick()
